// Bilingual content for M C Solutions Insurance LLC
const CONTENT = {
  es: {
    nav: ["Coberturas", "Cotizar", "Nosotros", "Servicios", "Contacto"],
    topbar: { hours: "Lun–Vie · 9:00 a 18:00", phone: "(555) 412-0809", license: "Lic. FL · TX · GA" },
    cta: { quote: "Cotizar en 2 minutos", agent: "Hablar con un agente", call: "Llamar ahora", explore: "Ver coberturas" },
    hero: {
      eyebrow: "Servicios de seguros · Establecidos 2024",
      title_a: "Cobertura con",
      title_b_it: "visión",
      title_c: "de águila.",
      sub: "Protegemos lo que mueve a tu familia y a tu negocio. Cotizaciones reales en minutos, agentes bilingües, y respuesta humana cuando un reclamo no puede esperar.",
      stat1: { k: "+2,400", v: "pólizas activas" },
      stat2: { k: "98%", v: "renovación anual" },
      stat3: { k: "<24h", v: "respuesta a reclamos" },
      live: "Agentes en línea",
    },
    intro: {
      kicker: "Quiénes somos",
      lead_a: "Una agencia independiente que",
      lead_it: "elige por ti",
      lead_b: " — comparamos más de 30 aseguradoras para encontrar la cobertura correcta al precio justo. Sin paquetes inflados ni letras pequeñas.",
    },
    coverage: {
      kicker: "Coberturas",
      heading_a: "Ocho frentes,",
      heading_it: "una cobertura tranquila.",
      lede: "Personal, comercial y especializada. Trabajamos con carriers admitidos y excedentarios para encajar el riesgo correcto.",
      items: [
        { num: "01", name: "Auto", tagline: "Tu vehículo, tu día a día.", body: "Liability, colisión, comprehensiva, SR-22, alquiler y asistencia en carretera. Descuentos por buen historial y multi-pólizas." , bullets: ["Liability mínima estatal", "Cobertura completa", "SR-22 / FR-44"] },
        { num: "02", name: "Hogar", tagline: "El techo donde todo importa.", body: "Vivienda, contenidos, responsabilidad personal y costos de vida adicional. Endosos por joyería, agua y huracán.", bullets: ["HO-3 estándar", "HO-6 condominio", "Inundación (NFIP)"] },
        { num: "03", name: "Vida", tagline: "Lo que dejas, lo que cuidas.", body: "Term, Whole y IUL. Sin examen médico para coberturas hasta $500,000 dependiendo del carrier y edad.", bullets: ["Term 10/20/30", "Whole Life", "Final Expense"] },
        { num: "04", name: "Salud", tagline: "Para ti y para tu familia.", body: "ACA / Marketplace, Medicare Advantage, suplementarios y dental. Inscripción especial si calificas.", bullets: ["ACA / Obamacare", "Medicare", "Visitantes"] },
        { num: "05", name: "Comercial", tagline: "Tu negocio, asegurado.", body: "BOP, GL, propiedad comercial, workers comp y autos comerciales. Para contratistas, food trucks, salones y más.", bullets: ["BOP", "Workers Comp", "Commercial Auto"] },
        { num: "06", name: "Trucking", tagline: "MC, DOT y todo el camino.", body: "Liability primaria, cargo, fisical damage, non-trucking liability. Filings 91X y BMC-91 incluidos.", bullets: ["Owner-Operator", "Fleet", "Cargo / FD"] },
        { num: "07", name: "Fianzas", tagline: "Bonds para contratistas.", body: "Performance, payment, license & permit y notario. Aprobación rápida con buen crédito.", bullets: ["Performance", "License & Permit", "Notary"] },
        { num: "08", name: "Sombrilla", tagline: "Por encima del límite.", body: "Cobertura adicional de $1M a $5M sobre auto, hogar y comercial cuando lo de base no alcanza.", bullets: ["Personal", "Comercial", "Multi-pólizas"] },
      ],
    },
    why: {
      kicker: "Por qué nosotros",
      heading_a: "El águila no",
      heading_it: "improvisa",
      heading_b: " — nosotros tampoco.",
      values: [
        { num: "I.", name: "Vigilancia", body: "Revisamos tu pólizas cada renovación. Si el mercado cambia, te lo decimos antes que el aviso del carrier." },
        { num: "II.", name: "Protección", body: "El alcance de tu cobertura no se decide por un script. Se decide por tu vida — número de hijos, propiedad, deuda, sueños." },
        { num: "III.", name: "Confianza", body: "Bilingüe de verdad. Inglés y español hablado y escrito. Sin traducciones automáticas que dejan dudas." },
      ],
    },
    process: {
      kicker: "Cómo funciona",
      heading_a: "De la pregunta a la",
      heading_it: "póliza activa",
      heading_b: ", en 4 pasos.",
      steps: [
        { n: "01", t: "Cuéntanos", d: "Llenas un formulario de 2 minutos o nos llamas. Una sola vez recopilamos lo necesario." },
        { n: "02", t: "Comparamos", d: "Cotizamos con 30+ aseguradoras admitidas. Solo las opciones que te sirven." },
        { n: "03", t: "Escoges", d: "Te explicamos en español, sin tecnicismos. Tú decides el balance entre prima y cobertura." },
        { n: "04", t: "Te respaldamos", d: "Si hay un reclamo, llamas a tu agente — no a un call center extranjero. Acompañamos hasta el cierre." },
      ],
    },
    quote: {
      kicker: "Cotizar",
      heading_a: "Una cotización",
      heading_it: "real",
      heading_b: ", no un estimado.",
      sub: "Sin compromiso. Sin pull de crédito hasta que tú lo autorices.",
      labels: { type: "Tipo de seguro", name: "Nombre completo", phone: "Teléfono", zip: "ZIP code", lang_pref: "Idioma de preferencia", consent: "Acepto que me contacten por teléfono o SMS sobre esta cotización." },
      placeholders: { name: "María Castaño", phone: "(305) 555-0123", zip: "33125" },
      submit: "Solicitar cotización",
      types: ["Auto", "Hogar", "Vida", "Salud", "Comercial", "Trucking", "Fianzas", "Sombrilla"],
      note: "Promedio de respuesta · 47 minutos en horario hábil",
    },
    testimonials: {
      kicker: "Clientes",
      heading_a: "Lo que dicen",
      heading_it: "ellos",
      heading_b: ".",
      items: [
        { q: "Llevaba tres años pagando una póliza que ni entendía. En una llamada de quince minutos me bajaron $86 al mes y subieron la cobertura. La diferencia se nota.", a: "Roberto G.", r: "Owner-Operator · Houston, TX", since: "Cliente desde 2024" },
        { q: "Tuvimos un incendio menor en la cocina del food truck. Llamé un domingo y el lunes tenía adjuster. Nadie me dijo \"call back Monday\". Eso no tiene precio.", a: "Lucía M.", r: "La Cocinita Food Truck · Miami, FL", since: "Cliente desde 2025" },
        { q: "Soy contratista y necesitaba un performance bond de $250K en 48 horas. Lo tuve en 31 horas. Me ganaron el cliente y la confianza.", a: "Jorge A.", r: "AC Contractors · Atlanta, GA", since: "Cliente desde 2024" },
      ],
    },
    contact: {
      kicker: "Contacto",
      heading_a: "Cuando una llamada",
      heading_it: "vale más",
      heading_b: " que un formulario.",
      cards: [
        { label: "Llámanos", value: "(555) 412-0809", sub: "Lun a Vie · 9:00 — 18:00 EST" },
        { label: "Escríbenos", value: "hola@mcsolutionsins.com", sub: "Respuesta en menos de 4 horas hábiles" },
        { label: "Visítanos", value: "1820 NW 27th Ave, Suite 410", sub: "Miami, FL 33125 · Cita previa recomendada" },
      ],
      after: "Después de horas",
      after_d: "Si es una emergencia (accidente, robo, incendio) llama directo al carrier. El número está en tu tarjeta y en nuestro portal de clientes 24/7.",
    },
    footer: {
      tag: "Servicios de seguros · Independiente",
      states: "Licenciados en Florida · Texas · Georgia",
      copy: "© 2026 M C Solutions Insurance LLC. Todos los derechos reservados.",
      links: ["Política de privacidad", "Accesibilidad", "Aviso legal", "Términos"],
      address: "1820 NW 27th Ave, Suite 410 · Miami, FL 33125",
      lic: "Florida Lic. P074-2024 · NPN 19384021",
    },
  },
  en: {
    nav: ["Coverage", "Get a quote", "About", "Services", "Contact"],
    topbar: { hours: "Mon–Fri · 9:00am to 6:00pm", phone: "(555) 412-0809", license: "Licensed FL · TX · GA" },
    cta: { quote: "Quote in 2 minutes", agent: "Talk to an agent", call: "Call now", explore: "See coverage" },
    hero: {
      eyebrow: "Insurance services · Established 2024",
      title_a: "Coverage with",
      title_b_it: "eagle",
      title_c: "vision.",
      sub: "We protect what moves your family and your business. Real quotes in minutes, bilingual agents, and human responses when a claim can't wait.",
      stat1: { k: "2,400+", v: "active policies" },
      stat2: { k: "98%", v: "renewal rate" },
      stat3: { k: "<24h", v: "claim response" },
      live: "Agents online",
    },
    intro: {
      kicker: "Who we are",
      lead_a: "An independent agency that",
      lead_it: "shops for you",
      lead_b: " — we compare 30+ carriers to land the right coverage at the right price. No bundled fluff, no fine-print surprises.",
    },
    coverage: {
      kicker: "Coverage",
      heading_a: "Eight fronts,",
      heading_it: "one quiet coverage.",
      lede: "Personal, commercial, and specialty. Admitted and surplus markets to match the right risk.",
      items: [
        { num: "01", name: "Auto", tagline: "Your vehicle, your daily life.", body: "Liability, collision, comprehensive, SR-22, rental and roadside assistance. Discounts for clean driving and bundling.", bullets: ["State minimum", "Full coverage", "SR-22 / FR-44"] },
        { num: "02", name: "Home", tagline: "The roof where it all matters.", body: "Dwelling, contents, personal liability and additional living expense. Endorsements for jewelry, water and hurricane.", bullets: ["HO-3 standard", "HO-6 condo", "Flood (NFIP)"] },
        { num: "03", name: "Life", tagline: "What you leave, what you guard.", body: "Term, Whole and IUL. No-exam coverage up to $500,000 depending on carrier and age.", bullets: ["Term 10/20/30", "Whole Life", "Final Expense"] },
        { num: "04", name: "Health", tagline: "For you and your family.", body: "ACA / Marketplace, Medicare Advantage, supplemental and dental. Special enrollment if you qualify.", bullets: ["ACA / Obamacare", "Medicare", "Visitor"] },
        { num: "05", name: "Commercial", tagline: "Your business, secured.", body: "BOP, GL, commercial property, workers comp and commercial auto. For contractors, food trucks, salons and more.", bullets: ["BOP", "Workers Comp", "Commercial Auto"] },
        { num: "06", name: "Trucking", tagline: "MC, DOT and the whole road.", body: "Primary liability, cargo, physical damage, non-trucking liability. 91X and BMC-91 filings included.", bullets: ["Owner-Operator", "Fleet", "Cargo / PD"] },
        { num: "07", name: "Bonds", tagline: "Bonds for contractors.", body: "Performance, payment, license & permit and notary. Fast approval with good credit.", bullets: ["Performance", "License & Permit", "Notary"] },
        { num: "08", name: "Umbrella", tagline: "Above the limit.", body: "Additional $1M–$5M coverage over auto, home and commercial when the base isn't enough.", bullets: ["Personal", "Commercial", "Multi-policy"] },
      ],
    },
    why: {
      kicker: "Why us",
      heading_a: "Eagles don't",
      heading_it: "improvise",
      heading_b: " — neither do we.",
      values: [
        { num: "I.", name: "Vigilance", body: "We re-shop your policies at every renewal. If the market shifts, you'll hear it from us before your carrier's notice." },
        { num: "II.", name: "Protection", body: "The scope of your coverage isn't decided by a script. It's decided by your life — kids, property, debt, dreams." },
        { num: "III.", name: "Trust", body: "Truly bilingual. English and Spanish — spoken and written. No machine translations that leave you guessing." },
      ],
    },
    process: {
      kicker: "How it works",
      heading_a: "From question to",
      heading_it: "active policy",
      heading_b: ", in 4 steps.",
      steps: [
        { n: "01", t: "Tell us", d: "You fill a 2-minute form or you call. We collect what we need, once." },
        { n: "02", t: "We shop", d: "We quote with 30+ admitted carriers. Only the options that fit you." },
        { n: "03", t: "You choose", d: "We explain in plain language, no jargon. You decide the balance between premium and coverage." },
        { n: "04", t: "We back you", d: "If there's a claim, you call your agent — not a foreign call center. We see it through to closing." },
      ],
    },
    quote: {
      kicker: "Quote",
      heading_a: "A real",
      heading_it: "quote",
      heading_b: ", not an estimate.",
      sub: "No commitment. No credit pull until you authorize it.",
      labels: { type: "Insurance type", name: "Full name", phone: "Phone", zip: "ZIP code", lang_pref: "Preferred language", consent: "I agree to be contacted by phone or SMS about this quote." },
      placeholders: { name: "Maria Castaño", phone: "(305) 555-0123", zip: "33125" },
      submit: "Request quote",
      types: ["Auto", "Home", "Life", "Health", "Commercial", "Trucking", "Bonds", "Umbrella"],
      note: "Average response · 47 minutes during business hours",
    },
    testimonials: {
      kicker: "Clients",
      heading_a: "What",
      heading_it: "they",
      heading_b: " say.",
      items: [
        { q: "I'd been paying three years for a policy I didn't even understand. In one fifteen-minute call they dropped me $86/month and raised my coverage. The difference shows.", a: "Roberto G.", r: "Owner-Operator · Houston, TX", since: "Client since 2024" },
        { q: "We had a small kitchen fire in the food truck. I called Sunday and had an adjuster Monday. Nobody told me \"call back Monday.\" That's priceless.", a: "Lucía M.", r: "La Cocinita Food Truck · Miami, FL", since: "Client since 2025" },
        { q: "I'm a contractor and needed a $250K performance bond in 48 hours. Got it in 31 hours. Won me the client and the trust.", a: "Jorge A.", r: "AC Contractors · Atlanta, GA", since: "Client since 2024" },
      ],
    },
    contact: {
      kicker: "Contact",
      heading_a: "When a phone call",
      heading_it: "is worth more",
      heading_b: " than a form.",
      cards: [
        { label: "Call us", value: "(555) 412-0809", sub: "Mon–Fri · 9:00am — 6:00pm EST" },
        { label: "Email us", value: "hello@mcsolutionsins.com", sub: "Reply within 4 business hours" },
        { label: "Visit us", value: "1820 NW 27th Ave, Suite 410", sub: "Miami, FL 33125 · By appointment recommended" },
      ],
      after: "After hours",
      after_d: "If it's an emergency (accident, theft, fire) call your carrier directly. The number is on your card and in our 24/7 client portal.",
    },
    footer: {
      tag: "Insurance services · Independent",
      states: "Licensed in Florida · Texas · Georgia",
      copy: "© 2026 M C Solutions Insurance LLC. All rights reserved.",
      links: ["Privacy policy", "Accessibility", "Legal notice", "Terms"],
      address: "1820 NW 27th Ave, Suite 410 · Miami, FL 33125",
      lic: "Florida Lic. P074-2024 · NPN 19384021",
    },
  },
};
window.CONTENT = CONTENT;
